services:
  - type: web
    name: patentsbrowser-frontend
    env: static
    buildCommand: npm install && npm run build:stage
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: "public, max-age=3600"
      - path: /assets/*
        name: Cache-Control
        value: "public, max-age=31536000"
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: VITE_NODE_ENV
        value: stage 