services:
  - type: web
    name: patentsbrowser-backend-stage
    env: node
    region: singapore
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=stage node -r dotenv/config dist/server.js dotenv_config_path=.env.stage
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: MONGODB_URI
        fromDatabase:
          name: patentsbrowser-db-stage
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false

  - type: web
    name: patentsbrowser-backend-prod
    env: node
    region: singapore
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node -r dotenv/config dist/server.js dotenv_config_path=.env.production
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: MONGODB_URI
        fromDatabase:
          name: patentsbrowser-db-prod
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false

databases:
  - name: patentsbrowser-db-stage
    plan: free
    region: singapore
    databaseName: patentsbrowser_stage
    user: patentsbrowser_stage_user

  - name: patentsbrowser-db-prod
    plan: free
    region: singapore
    databaseName: patentsbrowser_prod
    user: patentsbrowser_prod_user 